services:
  frontend_service:
    build:
      dockerfile: Dockerfile.dev
    container_name: frontend_service
    ports:
      - "8081:80"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=80