services:
  react:
    container_name: frontend
    build:
      context: frontend/
      dockerfile: Dockerfile.prod
    ports:
      - "8081:80"
    env_file:
      - .env
    networks:
      - transcend
    volumes:
      - ./frontend/:/app
      - /app/node_modules
    environment:
      - PORT=80
    
  django:
    container_name: backend
    build:
      context: backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    networks:
      - transcend
    depends_on:
      - postgresql
  
  postgresql:
    image: postgres:16
    container_name: database
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    networks:
      - transcend
    ports:
      - "5432:5432"

networks:
  transcend:
    name: transcend
    driver: bridge