# version: '3.8'

services:
  gateway_microservice:
    container_name: gateway_service
    build: ./app/gateway_service
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks: 
      transcendence:
        ipv4_address: 172.20.10.2
    depends_on:
      # - statistics_microservice
      # - user_profile_microservice
      # - matchmaking_microservice
      - game_microservice
      # - notifications_microservice
      - frontend_service

  # statistics_microservice:
  #   container_name: statistics_service
  #   build: ./app/statistics_service
  #   restart: always
  #   networks: 
  #     transcendence:
  #       ipv4_address: 172.20.10.3

  # user_profile_microservice:
  #   container_name: user_profile_service
  #   build: ./app/user_profile_service
  #   restart: always
  #   networks: 
  #     transcendence:
  #       ipv4_address: 172.20.10.4
      
  # matchmaking_microservice:
  #   container_name: matchmaking_service
  #   build: ./app/matchmaking_service
  #   restart: always
  #   networks: 
  #     transcendence:
  #       ipv4_address: 172.20.10.5

  game_django:
      extends:
        file: app/game_service/docker-compose.game.yml
        service: game_network
      depends_on:
        - game_postgres
      networks: 
        transcendence:
          ipv4_address: 172.20.10.6
  game_postgres:
      extends:
        file: app/game_service/docker-compose.game.yml
        service: game_network



  # notifications_microservice:
  #   container_name: notifications_service
  #   build: ./app/notifications_service
  #   restart: always
  #   networks: 
  #     transcendence:
  #       ipv4_address: 172.20.10.7

  # frontend:
  #   container_name: frontend
  #   build: ./app/frontend
  #   restart: always
  #   networks: 
  #     transcendence:
  #       ipv4_address: 172.20.10.8

  postgres_db:
    container_name: postgreSQL
    build: ./app/postgreSQL
    env_file:
      - .env
    environment:
      POSTGRES_DB: database_name
      POSTGRES_USER: karolina1
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - transcendence

volumes:
  postgres_data:

networks:
  transcendence:
      name: transcendence
      driver: bridge
      ipam:
        config:
          - subnet: 172.20.10.0/24
            gateway: 172.20.10.1


