services:
  react:
    container_name: frontend
    build:
      context: frontend/
      dockerfile: ${DOCKERFILE:-Dockerfile.dev}
    ports:
      - "8081:80"
    env_file:
      - .env
    volumes:
      - ./frontend/:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=80
    
  django:
    container_name: backend
    build:
      context: backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
  # postgresql:
  #   container_name: database

networks:
  net:
    name: net
    driver: bridge