services:
  nginx:
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - ./nginx/src:/usr/share/nginx/html

  react:
    build:
      context: ./react
      dockerfile: Dockerfile
    volumes:
      - ./react:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
