version: '3.8'

services:
  db_a:
    image: postgres:13
    environment:
      POSTGRES_DB: comments_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  microservice_a:
    build:
      context: ./pageA
      dockerfile: Dockerfile
    volumes:
      - ./pageA:/app
    ports:
      - "8000:8000"
    depends_on:
      db_a:
        condition: service_healthy
    command: python3 manage.py runserver 0.0.0.0:8000

  db_b:
    image: postgres:13
    environment:
      POSTGRES_DB: comments_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  microservice_b:
    build: ./pageB
    volumes:
      - ./pageB:/app
    ports:
      - "8001:8001"
    depends_on:
      db_b:
        condition: service_healthy
    command: python3 manage.py runserver 0.0.0.0:8001