services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    env_file:
      - ../../.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-karolina1}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123}
    ports:
      - "5432:5432"
    networks:
      - "game_network"
    restart: unless-stopped

#this is for going into the database
  game_pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - "game_network"
    restart: unless-stopped

  game_django:
    build: .
    container_name: game_service
    command: ./script.sh
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - "game_network"
    env_file:
      - ../../.env
    restart: unless-stopped

networks:
  game_network:
