services:
  user_django:
    build: .
    container_name: user_service
    command: ./script.sh
    ports:
      - "8000:8000"
    depends_on:
      - "postgres_user"
    networks:
      - "user_network"
    env_file:
      - ../../.env
    restart: unless-stopped

  nginx_gateway:
    container_name: nginx_gateway
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    # volumes:
    #   - ./nginx/nginx.conf:/etc/nginx/nginx.conf   # Map the NGINX config file
    depends_on:
      - user_django
    networks:
      - "user_network"
    restart: unless-stopped
  
networks:
  user_network: