services:
  notify_django:
    build: .
    container_name: notify_service
    ports:
      - "3000:3000"
    depends_on:
      - "redis"
    networks:
      - "notify_network"
    env_file:
      - ../../.env
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: notify_redis
    networks:
      - "notify_network"
  
networks:
  notify_network: