services:
  django:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.dev
        #dockerfile: Dockerfile
    command: ./script.sh
    env_file:
      - ../.env
    environment:
      DEBUG: ${DEBUG}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "8000:8000"
    networks:
      - transcend
    volumes:
      - ./:/app  # Mount the local user_service folder to /code inside the container
        #volumes:
        #  - ./backend:/app
    depends_on:
      - postgresql
    restart: unless-stopped
  
  postgresql:
    container_name: database
    image: postgres:16
    ports:
      - "5432:5432"
    env_file:
      - ../.env
    networks:
      - transcend
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}

networks:
  transcend:
    name: transcend
    driver: bridge
