# Generated by Django 4.2.16 on 2024-10-23 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_playerprofile_alter_match_player1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.playerprofile')),
            ],
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='matches',
            field=models.ManyToManyField(blank=True, related_name='players', through='users.PlayerMatch', to='users.match'),
        ),
    ]
