services:
  db:
    container_name: postgres
    image: postgres:16
    env_file:
      - ../../.env
    environment:
      POSTGRES_USER: karolina3
      POSTGRES_PASSWORD: 12345
      POSTGRES_HOST: postgres
      POSTGRES_DB: karolina3
      POSTGRES_PORT: 5432
    ports:
      - "5433:5432"
    networks:
      - "user_network"
    restart: unless-stopped

#this is for going into the database
  userprofile_pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_user
    environment:
      PGADMIN_DEFAULT_EMAIL: admin1@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - "db"
    networks:
      - "user_network"
    restart: unless-stopped

  user_django:
    build: .
    container_name: user_service
    command: ./script.sh
    ports:
      - "8000:8000"
    depends_on:
      - "db"
    networks:
      - "user_network"
    env_file:
      - ../../.env
    restart: unless-stopped

networks:
  user_network: