services:
  db:
    image: postgres:16
    container_name: postgres_user_db
    env_file:
      - ../../.env
    environment:
      USER: ${POSTGRES_USERPROFILE_USER:-karolina3}
      PASSWORD: ${POSTGRES_USERPROFILE_PASSWORD:-1234}
    ports:
      - "5434:5434"
    networks:
      - "userprofile_network"
    restart: unless-stopped

#this is for going into the database
  userprofile_pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_user
    environment:
      PGADMIN_DEFAULT_EMAIL: admin1@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8082:80"
    depends_on:
      - db
    networks:
      - "userprofile_network"
    restart: unless-stopped

  userprofile_django:
    build: .
    container_name: userprofile_service
    command: ./script_user.sh
    ports:
      - "7000:7000"
    depends_on:
      - db
    networks:
      - "userprofile_network"
    env_file:
      - ../../.env
    restart: unless-stopped

networks:
  userprofile_network:
    driver: bridge
